name: Backend CI

on:
    push: 
        branches: 
            - main
    pull_request: 
        branches: 
            - main

jobs:
    backend-check:
        runs-on: ubuntu-latest

        services:
            mongo:
                image: mongo:6
                ports:
                    - 27017:27017
                env:
                    MONGO_INITDB_ROOT_USERNAME: admin123
                    MONGO_INITDB_ROOT_PASSWORD: adminpass123

        steps:
            - name: Checkout code
              uses: actions/Checkout@v4

            - name: Setup Node.jobs
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm ci 

            - name: Verify app start
              run: npm start
                
              